#!/bin/bash
#
# (C) 2009 - Alan SCHNEIDER <shk.schneider@gmail.com>
# Distributed under GNU GPLv2+
#

find . -type f -name "*~" -exec rm -vf {} \;
find . -type f -name "#*#" -exec rm -vf {} \;
#find . -type f -name "*.orig" -exec rm -vf {} \;
#find . -type f -name "*.bak" -exec rm -vf {} \;
