#!/bin/bash
#
# htpasswd-perl -- replaces htpasswd
# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ -x perl ] && error "perl: Command not found." 1

function usage() {
    echo "Usage: `basename $0` [-c] passwordfile username [...]" >&2
    echo "       The -c flag creates a new file." >&2
    exit 1
}

function error() {
    echo $(basename $0)": "$1 >&2
    [ $2 -ne 0 ] && exit $2
}

[ $# -lt 2 ] && usage

NEW="false"
if [ $1 = "-c" ] ; then
    NEW="true"
    shift
fi

[ $# -lt 2 ] && usage

FILE=$1
if [ $NEW = "true" ] ; then
    DIR=$(dirname $FILE)
    [ ! -e $DIR ] && error $DIR": No such file or directory." 1
    [ ! -d $DIR ] && error $DIR": Is not a directory." 1
    [ ! -r $DIR ] && error $DIR": Permission denied." 1
    echo -n '' > $FILE
else
    [ ! -f $FILE ] && error $FILE": No such file or directory." 1
    [ -d $FILE ] && error $FILE": Is a directory." 1
    [ ! -r $FILE ] && error $FILE": Permission denied." 1
fi
shift

for USERNAME in $@ ; do
    VALID=$(echo $USERNAME | grep -E '^[a-zA-Z0-9][a-zA-Z0-9_\-]*[a-zA-Z0-9]$')
    if [ "_"$VALID = "_" ] ; then
        error $USERNAME": Name not valid ([a-zA-Z0-9][a-zA-Z0-9_-]*[a-zA-Z0-9])" 0
    else
        echo "Adding password for "$USERNAME
        echo -n "New password: "
        stty -echo
        read PASSWD_1
        stty echo
        echo
        echo -n "Re-type new password: "
        stty -echo
        read PASSWD_2
        stty echo
        echo
        if [ "_"$PASSWD_1 = "_"$PASSWD_2 ] ; then
	    EXISTS=$(grep -n ^$USERNAME: $FILE | cut -d':' -f1)
	    PASSWD=$(perl -le "print crypt($PASSWD_1, $USERNAME);")
            if [ "_"$EXISTS = "_" ] ; then
	        echo $USERNAME":"$PASSWD >> $FILE
            else
                sed -i $EXISTS"c$USERNAME:$PASSWD" $FILE
            fi
        else
	    error "They don't match, sorry." 0
        fi
    fi
done
