#!/bin/bash
#
# passgen -- randomly generates Unix password
# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

# Usage: passgen [length]

if [ $# -eq 1 ] ; then
    if [ "_`echo "$1" | egrep '^[0-9]+$'`" = "_" ] ; then
	echo "E: $1: Not a valid number." >&2 && exit 1
    fi
    LENGTH=$1
else
    # Default length
    LENGTH=16
fi

tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${LENGTH} | xargs
