#!/bin/bash
#
# (C) 2009-2011 - Alan SCHNEIDER <shk.schneider@gmail.com>
# Distributed under GNU GPLv2+
#

[ $# -ne 1 ] && echo "Usage: `basename $0` <MAX>" >&2 && exit 1

NB=$1
echo $[ ( $RANDOM % $NB  ) + 1 ]
