#!/bin/bash
#
# realpath -- retrieve a file real path
# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

if [ $# -eq 0 ] ; then
    echo $(basename `readlink -f .`)": "$(readlink -f .)
else
    for ARGV in $@ ; do
	echo $(basename $ARGV)": "$(readlink -f $ARGV)
    done
fi
