#!/bin/bash
#
# (C) 2009 - Alan SCHNEIDER <shk.schneider@gmail.com>
# Distributed under GNU GPLv2+
#

DISTRIB=$(lsb_release -i | awk '{printf $NF}')
VERSION=$(lsb_release -sr)" \""$(exec lsb_release -sc | sed 's/^[a-z]/\U&/')"\""
LANG=$(bash -c set | grep -E '^(LANG|LC_)' | cut -d'=' -f2 | cut -d'.' -f1)
CPU=$(cat /proc/cpuinfo | grep flags | grep lm > /dev/null && echo x86 || echo x64)
KERNEL=$(uname -sr | cut -d'-' -f1)

echo "GNU/Linux $DISTRIB $VERSION $CPU [$LANG] with $KERNEL"
