#!/bin/bash
#
# repeat -- re-code of zsh's repeat built-in
# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ $# -lt 2 ] && echo "Usage: `basename $0` <time> <command [...]>" >&2 && exit 1

PERIOD=$1
shift

while [ $PERIOD -gt 0 ] ; do
    $@
    PERIOD=$(($PERIOD - 1))
done
