#!/bin/bash
#
# (C) 2010 - Alan SCHNEIDER <shk.schneider@gmail.com>
# Distributed under GNU GPLv2+
#

[ $# -lt 2 ] && echo "Usage: `basename $0` <time> <command [...]>" >&2 && exit 1

PERIOD=$1
shift

while [ $PERIOD -gt 0 ] ; do
    $@
    PERIOD=$(($PERIOD - 1))
done
