#!/bin/bash
#
# (C) 2010 - Alan SCHNEIDER <shk.schneider@gmail.com>
# Distributed under GNU GPLv2+
#

INTERNAL=$(ifconfig  | grep "inet addr:" | grep Bcast | awk '{print $2}' | cut -d':' -f2)
EXTERNAL=$(wget -q -O- checkip.dyndns.org | sed -r 's/^.* ([0-9\.]+)<.*/\1/g')
echo "$INTERNAL $EXTERNAL"
