#!/bin/bash
#
# whatismyip -- retrieve your external IP from command line
# Copyright (C) 2010-2012  Alan "Shtark" SCHNEIDER
#                          <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ "_`which curl`" = "_" ] && echo "E: curl: Command not found." >&2 && exit 1

curl ifconfig.me/ip
