#!/bin/bash
#
# whatismyip -- retrieve your external IP from command line
# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ "_`which wget`" = "_" ] && echo "E: wget: Command not found." >&2 && exit 1

INTERNAL=$(cat /proc/net/arp | egrep '^[0-9]' | cut -d' ' -f1 | tr "\n" " " | sed -r 's/ $//')
EXTERNAL=$(wget -q -O- checkip.dyndns.org | sed -r 's/^.* ([0-9\.]+)<.*/\1/g')
echo "$INTERNAL $EXTERNAL"
