#!/bin/bash
#
# worldnumber -- retrieve the Human population on Earth from command line
# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

HUMANS=$(wget -q -O - http://www.census.gov/population/international/ | grep wclocknum | sed -r 's#^.*>([0-9,]+)<.*$#\1#')
echo -e "$HUMANS humans on earth"
