#!/bin/bash
#
# apt-ping -- ping your apt repositories
# Copyright (C) 2010-2012  Alan SCHNEIDER
#                          <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

OK=$(echo -e "[ \033[0;32mok\033[0;0m ]")
KO=$(echo -e "[ \033[0;31mko\033[0;0m ]")

[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "apt-ping: no network connection" >&2 && exit 1
[ -z "`which curl`" ] && echo "apt-ping: command 'curl' not found" >&2 && exit 1

function ping_apt() {
    HTTP_STATUS=$(curl -I "$URL" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
    [ -z "$HTTP_STATUS" ] && return
    if [ "$HTTP_STATUS" = "HTTP/200" ] ; then
	echo -ne "   $HTTP_STATUS $URL"
	OFFSET=$(echo "`tput cols` - `echo $URL | wc -c` + 2" | bc -q)
	printf "%${OFFSET}s\n" "$OK"
    elif [ "$HTTP_STATUS" = "HTTP/302" ] ; then
	LOCATION=$(curl -I "$URL" 2>/dev/null | grep -E '^Location' | tr -d "\r" | cut -d' ' -f2-)
	echo "-> $LOCATION"
	[ "$LOCATION" = "$URL" ] && echo "!!!!!"
	if [ -n "$LOCATION" ] ; then
	    HTTP_STATUS=$(curl -I "$LOCATION" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
	    ping_apt "$FILE" "$LINE" "$LOCATION"
	fi
    else
	echo -ne "   $HTTP_STATUS $URL ($FILE:$LINE)"
	OFFSET=$(echo "`tput cols` - `echo "$URL$FILE$LINE" | wc -c` - 2" | bc -q)
	printf "%${OFFSET}s\n" "$KO"
    fi
}

if [ $# -ne 0 ] ; then
    FILE=$(readlink -f "$1")
    echo " * Reading $FILE..."
    [ ! -e "$FILE" ] && echo "apt-ping: $FILE: no such file or directory" >&2 && continue
    [ -d "$FILE" ] && echo "apt-ping: $FILE: is a directory" >&2 && continue
    [ ! -r "$FILE" ] && echo "apt-ping: $FILE: permission denied" >&2 && continue
    grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
	while read REPOSITORY ; do
	    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
	    URL=$(echo $REPOSITORY | cut -d' ' -f3-)
	    ping_apt "$FILE" "$LINE" "$URL"
        done
else
    while read FILE ; do
	echo " * Reading $FILE..."
	[ ! -r "$FILE" ] && echo "apt-ping: $FILE: permission denied" >&2 && continue
	grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
	    while read REPOSITORY ; do
	    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
	    URL=$(echo $REPOSITORY | cut -d' ' -f3- | cut -d'/' -f1,2,3)
	    ping_apt "$FILE" "$LINE" "$URL"
        done
    done < <(find /etc/apt -type f -name "*.list")
fi
