#!/bin/bash
#
# deploy-skel -- deploy /etc/skel configuration
# Copyright (C) 2012  Alan SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

function usage() {
    echo "Usage: deploy-skel [--force] [user ...]" >&2
    echo "       Will never overwrite, unless --force is supplied" >&2
    echo "       Without users supplied, will loop through every user accounts (1000 <= uid <= 59999)" >&2
    exit 1
}

FORCE="false"
for ARGV in $@ ; do
    [ -z "$ARGV" ] && continue
    [ "$ARGV" == "--help" ] && usage
    [ "$ARGV" == "--force" ] && FORCE="true" && shift
done

function deploy_skel_for_user() {
    [ -z "$LINE" ] && return
    _USER=$(echo $LINE | cut -d':' -f1)
    _UID=$(echo $LINE | cut -d':' -f3)
    _HOME=$(echo $LINE | cut -d':' -f6)
    if [ $_UID -ge 1000 ] && [ $_UID -le 59999 ] ; then
	while read FILE ; do
	    FILENAME=$(basename "$FILE")
	    if [ "$FORCE" = "true" ] || [ ! -f "$_HOME/$FILENAME" ] ; then
		if [ "$FORCE" = "true" ] ; then
		    printf "[F] $_USER: $_HOME/$FILENAME\n"
		else
		    printf "$_USER: $_HOME/$FILENAME\n"
		fi
	        cp -r "$FILE" "$_HOME/" > /dev/null
		chown -R "$_USER:$_USER" "$_HOME/$FILENAME"
	    fi
	done < <(find /etc/skel -maxdepth 1 | sed '1d')
    fi
}

if [ $# -gt 0 ] ; then
    for LOGIN in $@ ; do
	LINE=$(egrep ^$LOGIN: /etc/passwd)
	deploy_skel_for_user
    done
else
    while read LINE ; do
	deploy_skel_for_user
    done < <(cat /etc/passwd)
fi

# EOF
