#!/bin/bash
#
# no-space-left-on-device -- cleanup some space
# Copyright (C) 2011-2012  Alan SCHNEIDER
#                          <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

echo " * Actual situation"

df -h /

[ `id -u` -ne 0 ] && echo "no-space-left-on-device: are you root, `id -un`?" >&2 && exit 1
[ -z "`which dpkg`" ] && echo "no-space-left-on-device: command 'dpkg' not found" >&2 && exit 1
[ -z "`which aptitude`" ] && echo "no-space-left-on-device: command 'aptitude' not found" >&2 && exit 1

echo " * Cleaning..."

echo "   dpkg --purge"
dpkg --purge $(COLUMNS=200 dpkg -l | grep "^rc" | tr -s ' ' | cut -d ' ' -f 2)

echo "   aptitude autoclean"
aptitude autoclean

echo "   aptitude clean"
aptitude clean
#find /var/cache/apt/archives -type f -name "*.deb" -exec rm -vf {} \;

echo "   empty trash"
rm -r -f /home/*/.local/share/Trash/files/*

echo "   old thumbnails"
find /home/*/.thumbnails -type f -atime +7 -exec rm {} \;

#echo "   old kernels"
#aptitude purge $(dpkg -l | grep '^ii  linux\-\(headers\|image\)\-[0-9]' | grep -v `uname -r` | cut -d' ' -f3)

echo "   localepurge"
[ -z "`which localepurge`" ] && aptitude install localepurge || dpkg-reconfigure localepurge

echo "Done"
