#!/bin/bash
#
# apt-get-key -- auto-retrieve missing PUBKEY
# Copyright (C) 2010-2011  Alan "Shtark" SCHNEIDER
#                          <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

echo " * Running aptitude update..."
ERRORS=$(aptitude update 2>&1 | grep "W: GPG error:" | awk '{print $NF}')
E=0
for ERROR in $ERRORS ; do
    E=$(($E + 1))
done
echo "   $E GPG error(s) found"
[ $E -eq 0 ] && exit 0
SERVER="keyserver.ubuntu.com"
echo " * Resolving with <$SERVER>..."
for ERROR in $ERRORS ; do
    KEY=$(echo $ERROR | rev | cut -c 1-8 | rev)
    echo "   GPG error: "$ERROR" -> keycode: "$KEY
    gpg --keyserver $SERVER --recv-key $KEY 2>/dev/null >&2
    gpg -a --export $KEY | apt-key add - 2>/dev/null >&2
done

echo "Done."

#chown -R root:root ~/.gnupg
#ERRORS=$(aptitude update 2>&1 | egrep 'W: GPG error:')
#KEY=$()
#gpg --keyserver keyserver.ubuntu.com --recv-key "$KEY"
#error: check internet, check keyserver.ubuntu.com
#error: 'ping: sendmsg: Operation not permitted' firewall problem
#gpg -a --export "$KEY" | sudo apt-key add -
