#!/bin/bash
#
# This script should be placed in /usr/sbin/
# chown root:root /usr/sbin/apt-get-key
# chmod 755 /usr/sbin/apt-get-key
#

[ `whoami` != "root" ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
if [ "_`which lsb_release`" = "_" ] ; then
    echo "E: lsb_release: Command not found" >&2
    echo "   This most certainly means that this script ain't for your distro." >&2
    exit 1
fi
[ "_`which curl`" = "_" ] && echo "E: curl: Command not found" >&2 && exit 1

echo " * Running aptitude update..."
ERRORS=$(aptitude update 2>&1 | grep "W: GPG error:" | awk '{print $NF}')
E=0
for ERROR in $ERRORS ; do
    E=$(($E + 1))
done
echo "   $E GPG error(s) found"
[ $E -eq 0 ] && exit 0
SERVER="keyserver.ubuntu.com"
echo " * Resolving with <$SERVER>..."
for ERROR in $ERRORS ; do
    KEY=$(echo $ERROR | rev | cut -c 1-8 | rev)
    echo "   GPG error: "$ERROR" -> keycode: "$KEY
    gpg --keyserver $SERVER --recv-key $KEY 2>/dev/null >&2
    gpg -a --export $KEY | apt-key add - 2>/dev/null >&2
done

echo "Done."

exit 0
