#!/bin/bash
#
# power_off -- set a timer to shutdown
# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
#                     <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ "_`which shutdown`" = "_" ] && echo "E: shutdown: Command not found" >&2 && exit 1

if [ $# -eq 0 ] ; then
    echo "E: Usage: `basename $0` <TIME>" >&2
    echo "          TIME can have a format dd:hh:mm, hh:mm, mm" >&2
    exit 1
elif [ "_`echo "$1" | egrep '^[0-9]+:[0-9]+:[0-9]+$'`" != "_" ] ; then
    # dd:hh:mm
    DAYS=$(echo "$1" | cut -d':' -f1)
    HOURS=$(echo "$1" | cut -d':' -f2)
    MINUTES=$(echo "$1" | cut -d':' -f3)
    echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
    shutdown -h +$(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
elif [ "_`echo "$1" | egrep '^[0-9]+:[0-9]+$'`" != "_" ] ; then
    # hh:mm
    DAYS=0
    HOURS=$(echo "$1" | cut -d':' -f1)
    MINUTES=$(echo "$1" | cut -d':' -f2)
    echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
    shutdown -h +$(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
elif [ "_`echo "$1" | egrep '^[0-9]+$'`" != "_" ] ; then
    # mm
    DAYS=0
    HOURS=0
    MINUTES=$(echo "$1")
    echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
    shutdown -h +$(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
else
    echo "E: Usage: `basename $0` <TIME>" >&2
    echo "          TIME can have a format dd:hh:mm, hh:mm, mm" >&2
    exit 1
fi
